theme: null #jekyll-theme-cayman #minima  # You can replace 'minima' with another theme like 'jekyll-theme-cayman'
title: "Ashkan Tashk"
description: "My personal webpage"
baseurl: ""
url: "https://ashkantashk.github.io"
markdown: kramdown
permalink: pretty
exclude: ["node_modules", "vendor"]
